// Launch policy + actual components, with deterministic timers and reduced motion.
const assert = require('assert').strict;
const fs = require('fs');
const { JSDOM } = require('jsdom');
const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'https://wairo.test/', pretendToBeVisual: true });
global.window = dom.window; global.document = dom.window.document;
Object.defineProperty(globalThis, 'navigator', { value: dom.window.navigator, configurable: true });
global.HTMLElement = dom.window.HTMLElement; global.Node = dom.window.Node;
global.Event = dom.window.Event; global.Image = dom.window.Image;
global.IS_REACT_ACT_ENVIRONMENT = true;
let reduced = false, invisible = false, motionListeners = [];
window.matchMedia = () => ({ matches: reduced, addEventListener: (_, fn) => motionListeners.push(fn), removeEventListener: (_, fn) => { motionListeners = motionListeners.filter(f => f !== fn); } });
Object.defineProperty(document, 'hidden', { get: () => invisible });
let timers = new Map(), timerId = 0;
window.setTimeout = (fn, ms) => { timers.set(++timerId, { fn, ms }); return timerId; };
window.clearTimeout = id => timers.delete(id);
const React = require('react'); const { act } = React;
const { createRoot } = require('react-dom/client');
const { BrandIntro, BRAND_CARDS } = require('./src/features/launch/BrandIntro.tsx');
const { LaunchExperience } = require('./src/features/launch/LaunchExperience.tsx');
const { BrandLoading } = require('./src/features/launch/BrandLoading.tsx');
const { INTRO_SEEN_KEY, CARD_DURATION_MS, shouldPlayIntro } = require('./src/features/launch/launchPolicy.ts');
let root, count = 0;
const pass = s => { count++; console.log('PASS ' + s); };
const by = id => document.querySelector(`[data-testid="${id}"]`);
const button = label => [...document.querySelectorAll('button')].find(b => b.textContent.trim() === label || b.getAttribute('aria-label') === label);
const click = async el => { assert.ok(el, 'button exists'); await act(async () => el.click()); };
const tick = async () => { const job = [...timers].find(([, t]) => t.ms === CARD_DURATION_MS); assert.ok(job, 'one card timer'); timers.delete(job[0]); await act(async () => job[1].fn()); };
async function mount(element, url = '/') {
  if (root) act(() => root.unmount());
  document.body.innerHTML = '<div id="boot-splash"></div><div id="root"></div>';
  window.history.replaceState(null, '', url);
  timers.clear(); root = createRoot(document.getElementById('root'));
  await act(async () => root.render(element));
}
const application = () => React.createElement(LaunchExperience, {}, React.createElement('main', {}, React.createElement('button', {}, 'Real app action')));
(async () => {
  assert.equal(BRAND_CARDS.length, 2);
  assert.ok(shouldPlayIntro('/', '', false));
  assert.ok(!shouldPlayIntro('/', '', true));
  for (const hash of ['#admin/members', '#wanderly/experience/real', '#shop/one', '#you', '#join/code']) assert.ok(!shouldPlayIntro('/', hash, false));
  for (const path of ['/c/real', '/s/shop', '/groups']) assert.ok(!shouldPlayIntro(path, '', false));
  for (const path of ['/intro', '/intro/', '/intro/index.html']) assert.ok(shouldPlayIntro(path, '', true));
  pass('exactly two cards, once-per-tab landing policy, replay route, deep-link bypass');

  window.sessionStorage.clear(); await mount(application());
  assert.equal(document.getElementById('boot-splash'), null);
  assert.ok(by('brand-intro')); assert.ok(document.querySelector('[data-wairo-app]').hidden);
  assert.equal(document.querySelectorAll('h1').length, 1);
  assert.ok(document.querySelector('h1').textContent.includes('Small starts.'));
  assert.ok(!by('brand-intro').textContent.includes('Brief'));
  await tick(); assert.ok(document.querySelector('h1').textContent.includes('Great plans.'));
  await tick(); assert.equal(by('brand-intro'), null);
  assert.ok(!document.querySelector('[data-wairo-app]').hidden);
  assert.equal(document.activeElement, document.querySelector('[data-wairo-app]'));
  assert.equal(window.sessionStorage.getItem(INTRO_SEEN_KEY), '1');
  assert.equal(timers.size, 0);
  await mount(application()); assert.equal(by('brand-intro'), null);
  pass('HTML handoff, two timed cards, automatic entry, focus restoration and no replay on reload');

  window.sessionStorage.clear(); await mount(application());
  await click(button('Skip intro ↗'));
  assert.equal(by('brand-intro'), null); assert.equal(timers.size, 0);
  pass('Skip opens the app immediately and cleans up the countdown');

  await mount(application(), '/intro');
  await click(button('Pause introduction')); assert.equal(timers.size, 0);
  await click(button('Show card 2')); assert.ok(document.querySelector('h1').textContent.includes('Great plans.'));
  await click(button('Show card 1')); assert.ok(document.querySelector('h1').textContent.includes('Small starts.'));
  await click(button('Play introduction')); assert.equal(timers.size, 1);
  await click(button('Meet your next plan→')); assert.ok(button('Enter Wairo→'));
  await click(button('Enter Wairo→'));
  assert.equal(window.location.pathname, '/'); assert.equal(window.location.hash, '#home');
  assert.equal(by('brand-intro'), null);
  pass('replay, pause/play, numbered navigation, Next and Enter Wairo all work');

  reduced = true; window.sessionStorage.clear(); await mount(application());
  assert.ok(by('brand-intro')); assert.equal(timers.size, 0);
  assert.ok(document.body.textContent.includes('Go at your pace'));
  await act(async () => by('brand-intro').dispatchEvent(new window.KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true })));
  assert.ok(document.querySelector('h1').textContent.includes('Great plans.'));
  await act(async () => by('brand-intro').dispatchEvent(new window.KeyboardEvent('keydown', { key: 'Escape', bubbles: true })));
  assert.equal(by('brand-intro'), null);
  pass('reduced motion never auto-advances; keyboard navigation and Escape are supported');

  reduced = false; window.sessionStorage.clear(); await mount(application());
  invisible = true; await act(async () => document.dispatchEvent(new window.Event('visibilitychange')));
  assert.equal(timers.size, 0);
  invisible = false; await act(async () => document.dispatchEvent(new window.Event('visibilitychange')));
  assert.equal(timers.size, 1);
  await act(async () => { window.history.replaceState(null, '', '/#admin'); window.dispatchEvent(new window.Event('hashchange')); });
  assert.equal(by('brand-intro'), null); assert.equal(window.location.hash, '#admin');
  pass('background tabs pause and navigation is never overwritten by a late intro timer');

  const originalGet = window.Storage.prototype.getItem, originalSet = window.Storage.prototype.setItem;
  window.Storage.prototype.getItem = () => { throw new Error('blocked'); };
  window.Storage.prototype.setItem = () => { throw new Error('blocked'); };
  await mount(application()); await click(button('Skip intro ↗'));
  assert.equal(by('brand-intro'), null);
  window.Storage.prototype.getItem = originalGet; window.Storage.prototype.setItem = originalSet;
  pass('blocked storage cannot trap someone behind the splash');

  await mount(React.createElement(BrandLoading));
  assert.equal(document.querySelector('[role="status"]').getAttribute('aria-label'), 'Opening Wairo Blue Avenue');
  const html = fs.readFileSync('index.html', 'utf8');
  assert.match(html, /<title>Wairo Blue Avenue<\/title>/);
  const firstPaint = html.slice(html.indexOf('<div id="boot-splash"'), html.indexOf('<div id="root"'));
  assert.ok(!firstPaint.includes('Brief') && !firstPaint.includes('#0a0a0a'));
  assert.match(firstPaint, /Blue Avenue/); assert.match(firstPaint, /boot-recovery/);
  const manifest = JSON.parse(fs.readFileSync('public/manifest.webmanifest'));
  assert.equal(manifest.name, 'Wairo Blue Avenue'); assert.equal(manifest.theme_color, manifest.background_color);
  for (const icon of manifest.icons) assert.ok(fs.existsSync('public' + icon.src));
  assert.ok(!fs.existsSync('public/intro/assets/index-BY8SE0xX.js'));
  const sw = fs.readFileSync('public/sw.js', 'utf8');
  assert.ok(sw.includes('wairo-shell-v3') && sw.includes("startsWith('/api/')"));
  const artSize = fs.statSync('src/assets/brand/wairo-build.webp').size + fs.statSync('src/assets/brand/wairo-go.webp').size;
  assert.ok(artSize < 120000, 'local imagery is compact enough for the initial load');
  pass('first paint, React loader, installed-app branding and icons agree; legacy intro retired; artwork under 120KB');
  act(() => root.unmount());
  console.log(`PASSED ${count} FAILED 0`);
})().then(() => process.exit(0)).catch(e => { console.error(e); process.exit(1); });
