"""initial schema — vendors, stock, movements, patrons, lists, groups, chat, tools, events, POS bridge

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 12:24:27.391449+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_handle', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('current_role', sa.Enum('SOURCING', 'SELLING', 'BOTH', 'DORMANT', name='vendorrole'), nullable=False),
    sa.Column('business_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('physical_location', sa.String(length=500), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('network_score', sa.Float(), nullable=False),
    sa.Column('total_stock_moved', sa.Integer(), nullable=False),
    sa.Column('total_sourced', sa.Integer(), nullable=False),
    sa.Column('total_supplied', sa.Integer(), nullable=False),
    sa.Column('parasitism_index', sa.Float(), nullable=False),
    sa.Column('has_pos_connected', sa.Boolean(), nullable=False),
    sa.Column('pos_system_type', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_patron', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.create_index(op.f('ix_vendors_vendor_handle'), 'vendors', ['vendor_handle'], unique=True)
    op.create_table('courier_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('courier_name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('STARTER', 'ESTABLISHED', 'MOGUL', name='patrontier'), nullable=False),
    sa.Column('total_vendors_managed', sa.Integer(), nullable=False),
    sa.Column('total_events_organized', sa.Integer(), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('specialization', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regions_active', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('pos_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('pos_type', sa.String(length=50), nullable=False),
    sa.Column('connection_name', sa.String(length=200), nullable=True),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('api_secret', sa.String(length=1000), nullable=True),
    sa.Column('store_id', sa.String(length=200), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('items_synced', sa.Integer(), nullable=False),
    sa.Column('sync_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_connections_vendor_id'), 'pos_connections', ['vendor_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('wholesale_price', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=False),
    sa.Column('bulk_discount_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('POS_SYNC', 'MANUAL_ENTRY', 'BULK_IMPORT', 'NETWORK_TRANSFER', name='stocksource'), nullable=False),
    sa.Column('pos_item_id', sa.String(length=100), nullable=True),
    sa.Column('last_pos_sync', sa.DateTime(), nullable=True),
    sa.Column('visible_to_network', sa.Boolean(), nullable=False),
    sa.Column('visible_to_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_category'), 'stock_items', ['category'], unique=False)
    op.create_index(op.f('ix_stock_items_vendor_id'), 'stock_items', ['vendor_id'], unique=False)
    op.create_index('ix_stock_items_vendor_pos_item', 'stock_items', ['vendor_id', 'pos_item_id'], unique=False)
    op.create_index('ix_stock_items_vendor_sku', 'stock_items', ['vendor_id', 'sku'], unique=False)
    op.create_table('tool_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('WAREHOUSE', 'TRANSPORT', 'COURIER', 'POPUP_SHOP', 'HOTEL_SOURCING', 'EQUIPMENT', 'PACKAGING', 'COLD_STORAGE', name='toolcategory'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('min_booking', sa.Integer(), nullable=False),
    sa.Column('deposit_required', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('capacity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('times_booked', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_listings_category'), 'tool_listings', ['category'], unique=False)
    op.create_table('vendor_connections',
    sa.Column('vendor_a_id', sa.UUID(), nullable=False),
    sa.Column('vendor_b_id', sa.UUID(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parasitism_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_a_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['vendor_b_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_a_id', 'vendor_b_id')
    )
    op.create_table('vendor_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group_type', sa.Enum('NICHE', 'REGIONAL', 'TRADE', 'SOURCING', 'EVENT', 'OPEN', name='grouptype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_vendor_id', sa.UUID(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('collective_stock_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vendor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('primary_goods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sourcing_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supply_capacity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_registration', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('warehouse_address', sa.Text(), nullable=True),
    sa.Column('operating_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_order_value', sa.Float(), nullable=True),
    sa.Column('accepts_bulk', sa.Boolean(), nullable=True),
    sa.Column('offers_credit', sa.Boolean(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('deals_made_in_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['vendor_groups.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'group_id', name='uq_group_member')
    )
    op.create_table('hotel_sourcing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_listing_id', sa.UUID(), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=True),
    sa.Column('proximity_to', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vendor_rate', sa.Float(), nullable=True),
    sa.Column('includes_storage', sa.Boolean(), nullable=False),
    sa.Column('meeting_room', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tool_listing_id'], ['tool_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('popup_shops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_listing_id', sa.UUID(), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_type', sa.String(length=100), nullable=True),
    sa.Column('foot_traffic_estimate', sa.Integer(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shared_spaces_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_listing_id'], ['tool_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_added', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_removed', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['pos_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_sync_logs_connection_id'), 'pos_sync_logs', ['connection_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('from_vendor_id', sa.UUID(), nullable=False),
    sa.Column('to_vendor_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['to_vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_from_vendor_id'), 'stock_movements', ['from_vendor_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_status'), 'stock_movements', ['status'], unique=False)
    op.create_index(op.f('ix_stock_movements_stock_item_id'), 'stock_movements', ['stock_item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_to_vendor_id'), 'stock_movements', ['to_vendor_id'], unique=False)
    op.create_table('transport_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_listing_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('max_volume_cbm', sa.Float(), nullable=True),
    sa.Column('routes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insurance_covered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tool_listing_id'], ['tool_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patron_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('max_vendors', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('entry_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_group_created', sa.Boolean(), nullable=False),
    sa.Column('creating_group_id', sa.UUID(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('total_stock_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creating_group_id'], ['vendor_groups.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('warehouse_rentals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_listing_id', sa.UUID(), nullable=False),
    sa.Column('renter_vendor_id', sa.UUID(), nullable=False),
    sa.Column('space_allocated', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['renter_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['tool_listing_id'], ['tool_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('room_type', sa.Enum('GROUP', 'DIRECT', 'DEAL', 'NICHE_TOPIC', 'VENDOR_LIST', name='chatroomtype'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('vendor_list_id', sa.UUID(), nullable=True),
    sa.Column('deal_stock_item_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('topic_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['deal_stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['vendor_groups.id'], ),
    sa.ForeignKeyConstraint(['vendor_list_id'], ['vendor_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('patron_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('vendor_list_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('max_vendors', sa.Integer(), nullable=False),
    sa.Column('registered_count', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.Float(), nullable=False),
    sa.Column('vendor_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['vendor_groups.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ),
    sa.ForeignKeyConstraint(['vendor_list_id'], ['vendor_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_table('vendor_list_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('vendor_list_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('role_in_list', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['vendor_list_id'], ['vendor_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'vendor_list_id', name='uq_vendor_list_member')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('shared_stock_id', sa.UUID(), nullable=True),
    sa.Column('deal_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['shared_stock_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sent_at'), 'chat_messages', ['sent_at'], unique=False)
    op.create_table('chat_room_participants',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'vendor_id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('booth_assignment', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'vendor_id', name='uq_event_vendor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    op.drop_table('chat_room_participants')
    op.drop_index(op.f('ix_chat_messages_sent_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('vendor_list_memberships')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_table('events')
    op.drop_table('chat_rooms')
    op.drop_table('warehouse_rentals')
    op.drop_table('vendor_lists')
    op.drop_table('transport_services')
    op.drop_index(op.f('ix_stock_movements_to_vendor_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_stock_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_status'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_from_vendor_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_pos_sync_logs_connection_id'), table_name='pos_sync_logs')
    op.drop_table('pos_sync_logs')
    op.drop_table('popup_shops')
    op.drop_table('hotel_sourcing')
    op.drop_table('group_memberships')
    op.drop_table('vendor_profiles')
    op.drop_table('vendor_groups')
    op.drop_table('vendor_connections')
    op.drop_index(op.f('ix_tool_listings_category'), table_name='tool_listings')
    op.drop_table('tool_listings')
    op.drop_index('ix_stock_items_vendor_sku', table_name='stock_items')
    op.drop_index('ix_stock_items_vendor_pos_item', table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_vendor_id'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_category'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_pos_connections_vendor_id'), table_name='pos_connections')
    op.drop_table('pos_connections')
    op.drop_table('patrons')
    op.drop_table('courier_registrations')
    op.drop_index(op.f('ix_vendors_vendor_handle'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
    # Enum types are created implicitly by create_table but not dropped by drop_table.
    bind = op.get_bind()
    for enum_name in ('vendorrole', 'stocksource', 'patrontier', 'grouptype', 'chatroomtype', 'toolcategory'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
