"""governance and shared benefits

Revision ID: 8de27a99801f
Revises: 0004
Create Date: 2026-09-30 11:30:21.361741+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005_governance'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'GOVERNANCE_UPDATE'")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'BENEFIT_UPDATE'")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'APPEAL_UPDATE'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("actor_type IN ('vendor', 'operator', 'admin', 'system')", name='ck_governance_audit_actor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_audit_events_created_at'), 'governance_audit_events', ['created_at'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_group', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by_type', sa.String(length=30), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_group', 'version', name='uq_rule_group_version')
    )
    op.create_index(op.f('ix_rule_versions_rule_group'), 'rule_versions', ['rule_group'], unique=False)
    op.get_bind().exec_driver_sql("""
        INSERT INTO rule_versions (id, rule_group, version, configuration, approved_by_type, effective_from, created_at)
        VALUES (
            '00000000-0000-0000-0000-000000000504', 'biashara_score', 4,
            '{"events":{"pick_completed":5,"verified_stock_save":3,"accepted_peer_answer":2,"vendor_no_show":-15,"confirmed_spam":-5},"decay_days":180,"tiers":{"listener":0,"poster":20,"organizer":60,"lender_eligible":120},"dimension_weights":{"fulfillment":0.45,"peer_help":0.20,"conduct":0.20,"activity":0.15},"penalizable_vendor_failures":["VENDOR_NO_SHOW"],"non_penalizable_failures":["SUPPLIER_NO_SHOW","SUPPLIER_SHORT_DELIVERY","SUPPLIER_QUALITY_FAILURE","TRANSPORT_DELAY","PSP_FAILURE","TELCO_FAILURE","PLATFORM_FAILURE","FORCE_MAJEURE","DISPUTED"]}'::jsonb,
            'initial_published_rules', now(), now()
        )
    """)
    op.create_table('biashara_score_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('failure_cause', sa.String(length=50), nullable=True),
    sa.Column('reversed_event_id', sa.UUID(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('points <> 0', name='ck_biashara_score_event_nonzero'),
    sa.ForeignKeyConstraint(['reversed_event_id'], ['biashara_score_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'event_type', 'reference', name='uq_biashara_score_reference')
    )
    op.create_index('ix_biashara_score_vendor_date', 'biashara_score_events', ['vendor_id', 'created_at'], unique=False)
    op.create_table('dual_approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('requested_by_vendor_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_vendor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'applied', 'expired')", name='ck_dual_approval_status'),
    sa.ForeignKeyConstraint(['approved_by_vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dual_approval_status_created', 'dual_approval_requests', ['status', 'created_at'], unique=False)
    op.create_table('governance_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('authority', sa.String(length=40), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('created_by_vendor_id', sa.UUID(), nullable=True),
    sa.Column('rule_version_before', sa.String(length=80), nullable=True),
    sa.Column('proposed_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('quorum_required', sa.Float(), nullable=False),
    sa.Column('approval_required', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('implementation_note', sa.Text(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('legal_entity_id', sa.UUID(), nullable=True),
    sa.Column('legal_basis', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(scope = 'zone' AND zone_id IS NOT NULL) OR scope = 'platform'", name='ck_governance_proposal_zone'),
    sa.CheckConstraint("authority IN ('advisory', 'operationally_binding', 'board_recommendation', 'cooperative_member_vote')", name='ck_governance_proposal_authority'),
    sa.CheckConstraint("scope IN ('zone', 'platform')", name='ck_governance_proposal_scope'),
    sa.CheckConstraint("status IN ('draft', 'open', 'passed', 'rejected', 'implemented', 'expired', 'cancelled')", name='ck_governance_proposal_status'),
    sa.CheckConstraint('approval_required >= 0 AND approval_required <= 1', name='ck_governance_proposal_approval'),
    sa.CheckConstraint('closes_at > opens_at', name='ck_governance_proposal_dates'),
    sa.CheckConstraint('quorum_required >= 0 AND quorum_required <= 1', name='ck_governance_proposal_quorum'),
    sa.ForeignKeyConstraint(['created_by_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['market_zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_governance_proposals_scope_status', 'governance_proposals', ['scope', 'zone_id', 'status', 'closes_at'], unique=False)
    op.create_index(op.f('ix_governance_proposals_zone_id'), 'governance_proposals', ['zone_id'], unique=False)
    op.create_table('network_benefit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=False),
    sa.Column('verified_by_vendor_id', sa.UUID(), nullable=False),
    sa.Column('event_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("metric_type IN ('fulfilled_purchase', 'verified_peer_help', 'governance_participation', 'reliability')", name='ck_network_benefit_metric'),
    sa.CheckConstraint('amount >= 0', name='ck_network_benefit_amount_nonnegative'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'metric_type', 'source_type', 'source_reference', name='uq_network_benefit_evidence')
    )
    op.create_index('ix_network_benefit_vendor_date', 'network_benefit_events', ['vendor_id', 'event_at'], unique=False)
    op.create_table('revenue_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.Column('gross_amount_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_fees_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recognized_at', sa.DateTime(), nullable=False),
    sa.Column('evidence_note', sa.Text(), nullable=False),
    sa.Column('created_by_vendor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('supplier_facilitation_fee', 'logistics_fee', 'subscription', 'sponsored_placement', 'financial_referral', 'market_report')", name='ck_revenue_source_type'),
    sa.CheckConstraint('gross_amount_ksh >= 0 AND payment_fees_ksh >= 0 AND net_amount_ksh >= 0', name='ck_revenue_amounts_nonnegative'),
    sa.CheckConstraint('net_amount_ksh = gross_amount_ksh - payment_fees_ksh', name='ck_revenue_net_math'),
    sa.ForeignKeyConstraint(['created_by_vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_reference', name='uq_revenue_source_reference')
    )
    op.create_table('vendor_activity_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('local_day', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'local_day', name='uq_vendor_activity_local_day')
    )
    op.create_index(op.f('ix_vendor_activity_days_local_day'), 'vendor_activity_days', ['local_day'], unique=False)
    op.create_index(op.f('ix_vendor_activity_days_vendor_id'), 'vendor_activity_days', ['vendor_id'], unique=False)
    op.create_table('vendor_appeals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('appeal_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to_vendor_id', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'acknowledged', 'under_review', 'upheld', 'partially_reversed', 'reversed')", name='ck_vendor_appeal_status'),
    sa.ForeignKeyConstraint(['assigned_to_vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendor_appeals_status_created', 'vendor_appeals', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_vendor_appeals_vendor_id'), 'vendor_appeals', ['vendor_id'], unique=False)
    op.create_table('vendor_data_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('data_class', sa.String(length=30), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('consent_reference', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("data_class IN ('public', 'network_only', 'zone_only', 'operator_restricted', 'financial_restricted', 'voice_private', 'aggregated_anonymous')", name='ck_vendor_consent_data_class'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'purpose', name='uq_vendor_consent_purpose')
    )
    op.create_index(op.f('ix_vendor_data_consents_vendor_id'), 'vendor_data_consents', ['vendor_id'], unique=False)
    op.create_table('allocation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('operations_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('vendor_pool_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('local_ops_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('dispute_reserve_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('training_fund_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('governance_proposal_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_vendor_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_vendor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending', 'approved', 'retired')", name='ck_allocation_policy_status'),
    sa.CheckConstraint('operations_rate + vendor_pool_rate + local_ops_rate + dispute_reserve_rate + training_fund_rate = 1', name='ck_allocation_rates_sum_one'),
    sa.CheckConstraint('operations_rate >= 0 AND vendor_pool_rate >= 0 AND local_ops_rate >= 0 AND dispute_reserve_rate >= 0 AND training_fund_rate >= 0', name='ck_allocation_rates_nonnegative'),
    sa.ForeignKeyConstraint(['approved_by_vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['governance_proposal_id'], ['governance_proposals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_allocation_policy_version')
    )
    op.create_table('council_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('representative_id', sa.UUID(), nullable=False),
    sa.Column('alternate_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_disclosure', sa.Text(), nullable=False),
    sa.Column('election_proposal_id', sa.UUID(), nullable=True),
    sa.Column('consecutive_term_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'active', 'completed', 'recalled')", name='ck_council_term_status'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_council_term_dates'),
    sa.ForeignKeyConstraint(['alternate_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['election_proposal_id'], ['governance_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['representative_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['market_zones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_council_terms_zone_id'), 'council_terms', ['zone_id'], unique=False)
    op.create_index('uq_council_active_zone', 'council_terms', ['zone_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('governance_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('voting_weight', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('eligibility_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("vote IN ('yes', 'no', 'abstain')", name='ck_governance_vote_choice'),
    sa.CheckConstraint('voting_weight = 1', name='ck_governance_one_vendor_one_vote'),
    sa.ForeignKeyConstraint(['proposal_id'], ['governance_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'vendor_id', name='uq_governance_vote_vendor')
    )
    op.create_index(op.f('ix_governance_votes_proposal_id'), 'governance_votes', ['proposal_id'], unique=False)
    op.create_index('ix_governance_votes_proposal_vote', 'governance_votes', ['proposal_id', 'vote'], unique=False)
    op.create_index(op.f('ix_governance_votes_vendor_id'), 'governance_votes', ['vendor_id'], unique=False)
    op.create_table('benefit_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('eligible_revenue_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('distributable_pool_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calculation_hash', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'calculating', 'review', 'approved', 'distributed', 'cancelled')", name='ck_benefit_period_status'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_benefit_period_dates'),
    sa.ForeignKeyConstraint(['policy_version'], ['allocation_policies.version'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('starts_at', 'ends_at', 'policy_version', name='uq_benefit_period_policy_window')
    )
    op.create_table('vendor_benefit_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benefit_period_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('fulfilled_purchase_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('verified_help_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('governance_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('reliability_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('final_weight', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('allocated_amount_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('distribution_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("distribution_method IN ('group_buy_credit', 'logistics_credit', 'training_credit', 'cash_if_permitted')", name='ck_benefit_distribution_method'),
    sa.CheckConstraint("status IN ('calculated', 'approved', 'issued', 'reversed')", name='ck_benefit_allocation_status'),
    sa.CheckConstraint('fulfilled_purchase_score >= 0 AND verified_help_score >= 0 AND governance_score >= 0 AND reliability_score >= 0 AND final_weight >= 0 AND allocated_amount_ksh >= 0', name='ck_benefit_allocation_nonnegative'),
    sa.ForeignKeyConstraint(['benefit_period_id'], ['benefit_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benefit_period_id', 'vendor_id', name='uq_benefit_period_vendor')
    )
    op.create_table('vendor_credit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('benefit_period_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount_ksh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=80), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("transaction_type IN ('credit_issued', 'credit_redeemed', 'credit_expired', 'credit_reversed')", name='ck_vendor_credit_transaction_type'),
    sa.CheckConstraint('amount_ksh > 0', name='ck_vendor_credit_amount_positive'),
    sa.ForeignKeyConstraint(['benefit_period_id'], ['benefit_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendor_credit_vendor_created', 'vendor_credit_ledger', ['vendor_id', 'created_at'], unique=False)
    op.add_column('vendors', sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
    op.add_column('vendors', sa.Column('fraud_suspended_at', sa.DateTime(), nullable=True))

    # Audit, score, evidence, revenue and credit ledgers are append-only even if
    # an operator reaches the database outside the API.
    op.get_bind().exec_driver_sql("""
        CREATE OR REPLACE FUNCTION reject_append_only_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION USING MESSAGE = concat('append-only ledger ', TG_TABLE_NAME, ' cannot be changed (operation ', TG_OP, ')');
        END;
        $$ LANGUAGE plpgsql;
    """)
    for table in ('governance_audit_events', 'biashara_score_events', 'vendor_credit_ledger', 'revenue_events', 'network_benefit_events'):
        op.execute(f'CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation()')
        op.execute(f'CREATE TRIGGER trg_{table}_no_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION reject_append_only_mutation()')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ('governance_audit_events', 'biashara_score_events', 'vendor_credit_ledger', 'revenue_events', 'network_benefit_events'):
        op.execute(f'DROP TRIGGER IF EXISTS trg_{table}_no_truncate ON {table}')
        op.execute(f'DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}')
    op.execute('DROP FUNCTION IF EXISTS reject_append_only_mutation()')
    op.drop_column('vendors', 'fraud_suspended_at')
    op.drop_column('vendors', 'phone_verified_at')
    op.drop_index('ix_vendor_credit_vendor_created', table_name='vendor_credit_ledger')
    op.drop_table('vendor_credit_ledger')
    op.drop_table('vendor_benefit_allocations')
    op.drop_table('benefit_periods')
    op.drop_index(op.f('ix_governance_votes_vendor_id'), table_name='governance_votes')
    op.drop_index('ix_governance_votes_proposal_vote', table_name='governance_votes')
    op.drop_index(op.f('ix_governance_votes_proposal_id'), table_name='governance_votes')
    op.drop_table('governance_votes')
    op.drop_index('uq_council_active_zone', table_name='council_terms', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_council_terms_zone_id'), table_name='council_terms')
    op.drop_table('council_terms')
    op.drop_table('allocation_policies')
    op.drop_index(op.f('ix_vendor_data_consents_vendor_id'), table_name='vendor_data_consents')
    op.drop_table('vendor_data_consents')
    op.drop_index(op.f('ix_vendor_appeals_vendor_id'), table_name='vendor_appeals')
    op.drop_index('ix_vendor_appeals_status_created', table_name='vendor_appeals')
    op.drop_table('vendor_appeals')
    op.drop_index(op.f('ix_vendor_activity_days_vendor_id'), table_name='vendor_activity_days')
    op.drop_index(op.f('ix_vendor_activity_days_local_day'), table_name='vendor_activity_days')
    op.drop_table('vendor_activity_days')
    op.drop_table('revenue_events')
    op.drop_index('ix_network_benefit_vendor_date', table_name='network_benefit_events')
    op.drop_table('network_benefit_events')
    op.drop_index(op.f('ix_governance_proposals_zone_id'), table_name='governance_proposals')
    op.drop_index('ix_governance_proposals_scope_status', table_name='governance_proposals')
    op.drop_table('governance_proposals')
    op.drop_index('ix_dual_approval_status_created', table_name='dual_approval_requests')
    op.drop_table('dual_approval_requests')
    op.drop_index('ix_biashara_score_vendor_date', table_name='biashara_score_events')
    op.drop_table('biashara_score_events')
    op.drop_index(op.f('ix_rule_versions_rule_group'), table_name='rule_versions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_governance_audit_events_created_at'), table_name='governance_audit_events')
    op.drop_table('governance_audit_events')
    # ### end Alembic commands ###
